name: flutter_application_1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 5.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.0
  google_sign_in: #^4.5.9
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: ios-fix-sign-in
      path: packages/google_sign_in/google_sign_in
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_core: ^0.4.0+9

flutter:
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
